<?php

namespace siteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SemestresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemestresRepository extends EntityRepository
{
}
