<?php

namespace CoursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChapitresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapitresRepository extends EntityRepository
{
}
