<?php

namespace CoursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SousChapitresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousChapitresRepository extends EntityRepository
{
}
